if(EXISTS "C:/Users/god79/source/repos/LR1Build/tests/lr1_tests[1]_tests.cmake")
  include("C:/Users/god79/source/repos/LR1Build/tests/lr1_tests[1]_tests.cmake")
else()
  add_test(lr1_tests_NOT_BUILT lr1_tests_NOT_BUILT)
endif()
