name: CodeChecks

on:
  push:
    branches: [ main, lr ]
  pull_request:
    branches: [ main, lr ]
  
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: Build & Make
      run: cd build && make
    - name: Run C/C++test
      uses: parasoft/run-cpptest-action@2.0.1